---
- name: 'Configure linux user'
  user:
    name: '{{ configure_user_name }}'
    password: '{{ configure_user_password }}'
    state: '{{ configure_user_state }}'
    shell: '{{ configure_user_shell }}'
    groups: '{{ configure_user_groups }}'
    update_password: '{{ configure_user_update_password }}'
