galaxy_info:
  author: Héctor Luaces
  description: A g
  license: MIT
  min_ansible_version: 2.4

  platforms:
  - name: Ubuntu
    versions:
    - bionic

  galaxy_tags:
  - spotify

dependencies: []
