---
# defaults file for role_template

configuration_files: []
#  # Files to be cloned to somewhere (destination dir will be created)
#  # These files are expected to be templates. The name should not contain
#  # the '.j2' extension.
#  - type: 'file'
#    src:
#    dest:
#    dest_owner:
#    dest_group:
#    dest_mode:
#    owner:
#    group:
#    mode:
#
#  # Repos to be cloned somewhere (destination dir will be created)
#  - type: 'repo'
#    accept_hostkey:
#    force:
#    key_file:
#    repo:
#    ssh_opts:
#    version:
#    dest:
#    dest_owner:
#    dest_group:
#    dest_mode:
#    owner:
#    group:
#    mode:
