---

# Required as Ubuntu ships with Python3 and not 2
ansible_python_interpreter: /usr/bin/python3

# System's timezone
configure_timezone: 'Europe/Madrid'

# Additional user to create
configure_user_name: 'dummy'
configure_user_password: "{{ 'dummy' | password_hash('sha512') }}"

# List of apt-keys to load from disk
# See "extra_packages" role.
extra_packages_keys:
  # Spotify
  - id: '931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90'
    keyserver: 'keyserver.ubuntu.com'

# List of apt-keys to load from URLs.
# See "extra_packages" role
extra_packages_keys_url:
  - url: 'https://dl.google.com/linux/linux_signing_key.pub'
  - url: 'https://download.sublimetext.com/sublimehq-pub.gpg'

# Extra apt repositories to add
# See "extra_packages" role
extra_packages_repositories:
  - name: 'google_chrome'
    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
  - name: 'sublime_text'
    repo: 'deb https://download.sublimetext.com/ apt/stable/'
  - name: 'spotify'
    repo: 'deb http://repository.spotify.com stable non-free'

# Extra APT packages to install
# See "extra_packages" role
extra_packages_list:
  # Everyday apps
  - {name: 'thunderbird'}
  - {name: 'firefox'}
  - {name: 'google-chrome-stable'}
  - {name: 'keepassxc' }
  - {name: 'spotify-client'}

  # Gaming
  - {name: 'steam'}

  # Programming
  - {name: 'sublime-text'}
  - {name: 'git'}
  - {name: 'vagrant'}
  - {name: 'virtualbox'}
  - {name: 'nodejs'}
  - {name: 'python'}
  - {name: 'python3'}
  - {name: 'python-pip'}
  - {name: 'python3-pip'}
  - {name: 'clang-format'}
  - {name: 'composer'}
  - {name: 'cppcheck'}
  - {name: 'php'}
  - {name: 'sqlite3'}
  - {name: 'fonts-firacode'}

  # CLI
  - {name: 'terminator'}
  - {name: 'iotop'}
  - {name: 'mysql-client'  }
  - {name: 'strace'}
  - {name: 'telnet'}
  - {name: 'unrar'}
  - {name: 'unzip'}
  - {name: 'vim'}
  - {name: 'nmap'}

  # Media
  - {name: 'vlc'}
  - {name: 'gimp'}

   # System utils
  - {name: 'p7zip'}

# Snap packages to install
extra_packages_snaps:
  - name: 'discord'
  - name: 'phpstorm'
    classic: true

# Pip packages to install
extra_packages_pip:
  - name: 'ansible'
  - name: 'ansible-lint'
  - name: 'molecule'
  - name: 'flake8'
  - name: 'yamllint'

# As of now there's no stable docker for 19.04
docker_apt_release_channel: 'test'

# Docker users
docker_users: ["{{ configure_user_name }}"]

# Git configuration for the .gitconfig file
git_config:
  user:
    name: 'Héctor Luaces'
    email: "{{ vault_email }}"
  core:
    editor: 'vi'
    excludesfile: '~/.gitignore'
  web:
    browser: 'google-chrome'
  color:
    diff: 'auto'
    status: 'auto'
    branch: 'auto'
    interactive: 'auto'
    ui: 'true'
    pager: 'true'

# Configuration files for the newly created user
configuration_files_user:
  - type: 'file'
    dest: '~/.thunderbird/'
    src: 'thunderbird/profiles.ini'
  - type: 'file'
    dest: "~/.thunderbird/{{ configure_user_name }}.default"
    src: 'thunderbird/prefs.js'
