---
# tasks file for role_template

- name: 'Configure timezone'
  timezone: name="{{ configure_timezone }}"

- name: 'Configure linux user'
  user:
    name: '{{ configure_user_name }}'
    password: '{{ configure_user_password }}'
    state: '{{ configure_user_state }}'
    shell: '{{ configure_user_shell }}'
    groups: '{{ configure_user_groups }}'
    update_password: '{{ configure_user_update_password }}'

- name: 'Install base packages'
  apt:
    name: "{{ item }}"
    state: 'present'
  loop:
    - ubuntu-restricted-extras
    - gnome-tweak-tool
    - apt-transport-https

- name: 'Disable apt-daily services to unlock dpkg'
  systemd: name='{{ item }}' state='stopped' enabled='no'
  loop: "{{ apt_lock_holders }}"
  notify: ['enable apt_lock_holders']

- name: 'Stop apt-daily-upgrade.timer'
  systemd: name='apt-daily-upgrade.timer' state='stopped' enabled='no'

- name: 'Update Ubuntu Drivers'
  command: 'ubuntu-drivers autoinstall'
  when: ansible_virtualization_role != 'guest'
