---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: debian/stretch64
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 443, host: 8080"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    v: true
    'vault-password-file': "~/.ansible/default.vault"
verifier:
  name: testinfra
  lint:
    name: flake8
