---
- name: 'Build vendor packages'
  import_playbook: 0_local_requirements.yaml

- name: 'Intall Ubuntu Workstation'
  hosts: ubuntu,vagrant
  remote_user: "{{ remote_user|default('vagrant') }}"
  become: yes
  vars_files: ['../config/config.default.yml']
  roles:
    - role: configure_system
      tags: ['role-configure_system']
    - role: extra_packages
      tags: ['role-extra_packages']
    - role: geerlingguy.docker
      tags: ['role-geerlingguy.docker']
