---
- name: 'Build vendor packages'
  import_playbook: 0_local_requirements.yaml

- name: 'Install Ubuntu Workstation (root configuration)'
  hosts: ubuntu
  remote_user: "{{ remote_user|default('vagrant') }}"
  become: yes
  vars_files:
    - '../config/vault_secrets.yml'
    - '../config/config.default.yml'
  roles:
    - role: configure_system
      tags: ['role-configure_system']
    - role: extra_packages
      tags: ['role-extra_packages']
    - role: geerlingguy.docker
      tags: ['role-geerlingguy.docker']
    # Root dotfiles
    - role: dotfiles
      tags: ['role-dotfiles']

- name: 'Install Ubuntu Workstation (non root configuration)'
  hosts: ubuntu
  remote_user: "{{ remote_user|default('vagrant') }}"
  become: yes
  become_user: "{{ configure_user_name }}"
  vars_files:
    - '../config/vault_secrets.yml'
    - '../config/config.default.yml'
  roles:
    - role: dotfiles
      tags: ['role-dotfiles']
    - role: configuration_files
      tags: ['role-configuration_files']
      vars:
        configuration_files: "{{ configuration_files_user }}"
