---
- name: "Configure Spotify package"
  include_tasks: "install.yml"

- name: "Configure Spotify preferences"
  include_tasks: "configure.yml"
  when: spotify_state == 'present'

- name: "Remove Spotify preferences"
  include_tasks: "uninstall.yml"
  when: spotify_state == 'absent'
